package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"

	"gorm.io/gorm"

	"camstuart/talent-hound/internal/models"
	"camstuart/talent-hound/internal/platform"
	"camstuart/talent-hound/internal/profile"
	"camstuart/talent-hound/internal/scrub"
)

// Searcher is the role-listing provider. An interface because everything this
// phase asserts is about what leaves the machine and what comes back, and a
// fake server answers that faster and more completely than the real one.
type Searcher interface {
	Search(ctx context.Context, query string, limit int, cursor string) (*platform.SearchResponse, error)
}

// Clock supplies the current time, so the thirty-day and closing-date
// boundaries are tests rather than a wait.
type Clock func() time.Time

// DiscoveryService finds public role listings.
//
// This is the first phase where something leaves the machine, and every rule in
// it follows from that. A query built from a candidate's profile is a
// disclosure: it is scrubbed of direct identifiers, organizations are
// generalized, and the recruiter sees the exact bytes before anything is sent.
type DiscoveryService struct {
	db *gorm.DB
	// exa, when set, is used instead of building a client for the stored
	// credential. Only tests set it: a real search reads the key at the moment
	// of the request, because a client built at start-up holds whatever the
	// credential was then — which, at start-up, is nothing.
	exa       Searcher
	out       *outbound
	profiles  *CandidateProfileService
	criteria  *CriteriaService
	records   *RecordService
	artifacts *ArtifactService
	now       Clock
}

// NewDiscoveryService wires discovery to the profile gate and the criteria.
func NewDiscoveryService(
	db *gorm.DB, exa Searcher, profiles *CandidateProfileService,
	criteria *CriteriaService, records *RecordService, artifacts *ArtifactService,
	credentials *CredentialService,
) *DiscoveryService {
	return &DiscoveryService{
		db: db, exa: exa, profiles: profiles, criteria: criteria,
		records: records, artifacts: artifacts,
		out: &outbound{db: db, credentials: credentials},
		now: func() time.Time { return time.Now().UTC() },
	}
}

// searchTimeout bounds one provider call.
const searchTimeout = 30 * time.Second

// staleAfter is how long a listing stays current without being seen again.
const staleAfter = 30 * 24 * time.Hour

// aspectTypesForQuery are the professional aspects a query may draw on.
//
// Location and compensation are absent for the same reason they are absent from
// criteria proposals: they describe where a person has been and what they were
// paid, which is history rather than what they can do.
var aspectTypesForQuery = []profile.AspectType{
	profile.Skill, profile.Responsibility, profile.Experience,
	profile.Qualification, profile.Seniority,
}

// QueryPreview is the exact text that would be sent, and what is worrying
// about it.
type QueryPreview struct {
	// Query is the request. Sending transmits this unchanged — there is no
	// template applied later, because a preview generated by one code path and
	// a request built by another will diverge.
	Query string `json:"query"`
	// OrganizationWarning is set when the query names a specific organization.
	// Allowed, and worth knowing.
	OrganizationWarning string `json:"organizationWarning"`
	// IdentifierWarning is the serious one: the query appears to contain
	// something that identifies the candidate.
	IdentifierWarning string `json:"identifierWarning"`
}

// Preview builds a query from approved evidence and criteria, and writes
// nothing.
func (s *DiscoveryService) Preview(initiativeID, candidateID uint) (*QueryPreview, error) {
	parts := []string{}

	if candidateID != 0 {
		ready, err := s.profiles.Readiness(candidateID)
		if err != nil {
			return nil, err
		}
		if !ready.Ready {
			return nil, fmt.Errorf("a query is built from approved evidence: %s", ready.Reason)
		}
		approved, err := s.profiles.Approved(candidateID)
		if err != nil {
			return nil, err
		}
		if approved != nil {
			for _, a := range approved.Aspects {
				if !containsType(aspectTypesForQuery, profile.AspectType(a.Type)) {
					continue
				}
				parts = append(parts, a.Wording)
			}
		}
	}

	criteria, err := s.criteria.List(initiativeID)
	if err != nil {
		return nil, err
	}
	for _, c := range criteria {
		parts = append(parts, c.Text)
	}
	if len(parts) == 0 {
		return nil, fmt.Errorf("there is nothing to search for yet — approve a profile or add criteria first")
	}

	ids, err := s.identifiers(candidateID)
	if err != nil {
		return nil, err
	}
	// Scrub first, then generalize: removing the person, then removing the
	// places. Both happen before the recruiter sees it, so the default requires
	// no action to be safe.
	joined := strings.Join(parts, ", ")
	query := scrub.Generalize(scrub.Text(joined, ids))

	return s.out.describe(query, ids), nil
}

// Inspect reports what is worrying about a query the recruiter has edited.
func (s *DiscoveryService) Inspect(candidateID uint, query string) (*QueryPreview, error) {
	ids, err := s.identifiers(candidateID)
	if err != nil {
		return nil, err
	}
	return s.out.describe(query, ids), nil
}

// identifiers gathers a candidate's direct identifiers, for removal and for
// detection.
func (s *DiscoveryService) identifiers(candidateID uint) (scrub.Identifiers, error) {
	if candidateID == 0 {
		return scrub.Identifiers{}, nil
	}
	c, err := s.records.GetCandidate(candidateID)
	if err != nil {
		return scrub.Identifiers{}, err
	}
	names := []string{c.FullName}
	if c.PreferredName != "" {
		names = append(names, c.PreferredName)
	}
	return scrub.Identifiers{
		Names:   names,
		Emails:  c.Emails,
		Phones:  c.Phones,
		Address: c.Location,
	}, nil
}

// SendInput is a confirmed search.
type SendInput struct {
	InitiativeID uint `json:"initiativeId"`
	CandidateID  uint `json:"candidateId"`
	// Query is exactly what the recruiter confirmed. It is transmitted
	// unchanged.
	Query string `json:"query"`
	Limit int    `json:"limit"`
}

// SearchOutcome is what a sent search produced.
type SearchOutcome struct {
	SearchID uint `json:"searchId"`
	// RoleIDs are the roles this search created or updated, in result order.
	RoleIDs []uint `json:"roleIds"`
	Created int    `json:"created"`
	Updated int    `json:"updated"`
	Skipped int    `json:"skipped"`
	// Partial says some records could not be read.
	Partial bool `json:"partial"`
}

// Send transmits the confirmed query and caches what comes back.
//
// There is no cancel path here, and that is deliberate: cancelling is not
// calling this. An audit event for a search that did not happen would record a
// disclosure that did not occur, which is the one direction an audit log must
// never be wrong in.
func (s *DiscoveryService) Send(in SendInput) (*SearchOutcome, error) {
	query := in.Query
	if strings.TrimSpace(query) == "" {
		return nil, fmt.Errorf("there is no query to send")
	}
	if in.InitiativeID == 0 {
		return nil, fmt.Errorf("a search belongs to an initiative")
	}

	ctx, cancel := context.WithTimeout(context.Background(), searchTimeout)
	defer cancel()

	sentAt := s.now()
	searcher, err := s.searcher()
	if err != nil {
		// Nothing left the machine, so there is no disclosure to record — but
		// the recruiter pressed send, and a search that vanishes is worse than
		// one that failed. The attempt is recorded; the disclosure is not.
		record := models.Search{
			InitiativeID:  in.InitiativeID,
			Provider:      models.ProviderExa,
			Task:          models.TaskRoleSearch,
			Query:         query,
			SentAt:        sentAt,
			FailureReason: models.ReasonUnauthorized,
		}
		if writeErr := s.db.Create(&record).Error; writeErr != nil {
			return nil, fmt.Errorf("recording the search: %w", writeErr)
		}
		return nil, err
	}
	resp, sendErr := searcher.Search(ctx, query, in.Limit, "")

	// The request was transmitted, so the disclosure happened — whether or not
	// the provider then answered usefully.
	if err := s.recordDisclosure(sentAt, in); err != nil {
		return nil, err
	}

	record := models.Search{
		InitiativeID: in.InitiativeID,
		Provider:     models.ProviderExa,
		Task:         models.TaskRoleSearch,
		Query:        query,
		SentAt:       sentAt,
	}
	if sendErr != nil {
		record.FailureReason = searchReason(sendErr)
		if err := s.db.Create(&record).Error; err != nil {
			return nil, fmt.Errorf("recording the search: %w", err)
		}
		return nil, sendErr
	}

	record.ResultCount = len(resp.Results)
	record.SkippedCount = resp.Skipped
	record.Partial = resp.Skipped > 0
	if err := s.db.Create(&record).Error; err != nil {
		return nil, fmt.Errorf("recording the search: %w", err)
	}

	out := &SearchOutcome{SearchID: record.ID, Partial: record.Partial, Skipped: resp.Skipped}
	seen := map[uint]bool{}
	for _, r := range resp.Results {
		roleID, created, err := s.observe(r, sentAt)
		if err != nil {
			return nil, err
		}
		if seen[roleID] {
			// The same listing twice in one response is one role.
			continue
		}
		seen[roleID] = true
		out.RoleIDs = append(out.RoleIDs, roleID)
		if created {
			out.Created++
		} else {
			out.Updated++
		}
	}
	return out, nil
}

// recordDisclosure writes the audit event: that information left, never what.
func (s *DiscoveryService) recordDisclosure(at time.Time, in SendInput) error {
	event := models.DisclosureEvent{
		OccurredAt: at,
		Provider:   models.ProviderExa,
		Task:       models.TaskRoleSearch,
		// Names of kinds, never the things themselves.
		Categories: s.categories(in),
	}
	if in.InitiativeID != 0 {
		id := in.InitiativeID
		event.InitiativeID = &id
	}
	if in.CandidateID != 0 {
		id := in.CandidateID
		event.CandidateID = &id
	}
	return s.out.record(event)
}

// searcher is the client this search will use.
//
// Built here, per request, from the credential in the operating system's store.
// It used to be built once at start-up with an empty key and never touched
// again — so every search this application could ever make was refused for a
// missing credential, whatever the recruiter had since stored. A key read at
// start-up is a key read before the recruiter has entered one.
func (s *DiscoveryService) searcher() (Searcher, error) {
	if s.exa != nil {
		return s.exa, nil
	}
	key, err := s.out.key(models.ProviderExa)
	if err != nil {
		return nil, err
	}
	return platform.NewExa(key), nil
}

// categories names what kinds of thing this query disclosed.
//
// It used to be a constant reading "professional requirements, search criteria",
// which is what a generated query carries and not what every query carries. The
// recruiter may edit one, and the design lets them: an organization name is
// allowed outright and a direct identifier is permitted after a warning that
// says sending it discloses who the candidate is. Both were then recorded as
// though neither had happened.
//
// A disclosure record is the evidence that every non-local request was what it
// was supposed to be. One that understates what left the machine is worse than
// none, because it is the thing somebody would check instead of looking.
//
// Kinds, never the things themselves: that an identifier was sent, never which.
func (s *DiscoveryService) categories(in SendInput) string {
	kinds := []string{"professional requirements", "search criteria"}
	ids, err := s.identifiers(in.CandidateID)
	if err != nil {
		// The record is still made. A disclosure that happened is not made not
		// to have happened by a lookup failing afterwards.
		return strings.Join(append(kinds, "unverified content"), ", ")
	}
	return s.out.categories(kinds, in.Query, ids)
}

// observe resolves a result to a role and applies the source-observation rules.
func (s *DiscoveryService) observe(r platform.SearchResult, at time.Time) (uint, bool, error) {
	hash := fingerprint(r.Text)
	role, err := s.resolve(r, hash)
	if err != nil {
		return 0, false, err
	}

	if role == nil {
		created := models.Role{
			Title:          firstNonEmpty(r.Title, "Untitled listing"),
			CanonicalURL:   r.URL,
			SourceID:       r.SourceID,
			Source:         models.ProviderExa,
			Origin:         models.RoleOriginDiscovered,
			LifecycleState: models.RoleActive,
			PublishedOn:    models.Date(r.PublishedOn),
			ClosingOn:      models.Date(r.ClosingOn),
			RetrievedOn:    models.Date(at.Format("2006-01-02")),
			ContentHash:    hash,
			RetrievedAt:    &at,
		}
		if err := s.db.Create(&created).Error; err != nil {
			return 0, false, fmt.Errorf("storing the discovered role: %w", err)
		}
		if err := s.storeSource(created.ID, r, at, false); err != nil {
			return 0, false, err
		}
		return created.ID, true, nil
	}

	// Rediscovery. Same content is not an event: the retrieval time moves and
	// nothing derived is invalidated, because nothing it was derived from
	// changed.
	updates := map[string]any{
		"retrieved_at":    at,
		"retrieved_on":    at.Format("2006-01-02"),
		"lifecycle_state": models.RoleActive,
	}
	if r.ClosingOn != "" {
		updates["closing_on"] = r.ClosingOn
	}
	if hash != "" && hash != role.ContentHash {
		// The listing changed. A new immutable current source, the previous one
		// made historical, and everything derived goes stale — which the role
		// profile computes for itself from the source hash.
		updates["content_hash"] = hash
		if err := s.historicize(role.ID); err != nil {
			return 0, false, err
		}
		if err := s.storeSource(role.ID, r, at, false); err != nil {
			return 0, false, err
		}
	}
	if err := s.db.Model(&models.Role{}).Where("id = ?", role.ID).Updates(updates).Error; err != nil {
		return 0, false, fmt.Errorf("updating role %d: %w", role.ID, err)
	}
	return role.ID, false, nil
}

// resolve finds the role a result belongs to, by a fixed precedence.
//
// Source ID, then canonical URL, then content fingerprint. Precedence rather
// than scoring: a scored match fails as two roles that are the same, or one
// role that is two, discovered weeks later when a match cites the wrong
// listing.
func (s *DiscoveryService) resolve(r platform.SearchResult, hash string) (*models.Role, error) {
	find := func(where string, args ...any) (*models.Role, error) {
		var row models.Role
		err := s.db.Where(where, args...).Order("id asc").First(&row).Error
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		if err != nil {
			return nil, fmt.Errorf("resolving role identity: %w", err)
		}
		return &row, nil
	}
	if r.SourceID != "" {
		if role, err := find("source_id = ? AND source_id <> ''", r.SourceID); role != nil || err != nil {
			return role, err
		}
	}
	if r.URL != "" {
		if role, err := find("canonical_url = ? AND canonical_url <> ''", r.URL); role != nil || err != nil {
			return role, err
		}
	}
	if hash != "" {
		if role, err := find("content_hash = ? AND content_hash <> ''", hash); role != nil || err != nil {
			return role, err
		}
	}
	return nil, nil
}

// storeSource attaches the provider's content to the role as an artifact.
func (s *DiscoveryService) storeSource(roleID uint, r platform.SearchResult, at time.Time, pasted bool) error {
	if strings.TrimSpace(r.Text) == "" {
		// Nothing to store. The recruiter can paste the listing, which is the
		// honest fallback rather than an empty artifact pretending to be one.
		return nil
	}
	source := "exa"
	if pasted {
		source = "recruiter paste"
	}
	name := firstNonEmpty(r.Title, r.URL, fmt.Sprintf("listing %s", at.Format("2006-01-02")))
	_, err := s.artifacts.create(name, "", source, []byte(r.Text), models.LinkRole, roleID)
	if err != nil {
		return fmt.Errorf("storing the listing content: %w", err)
	}
	return nil
}

// historicize marks a role's current sources as superseded.
func (s *DiscoveryService) historicize(roleID uint) error {
	err := s.db.Model(&models.ArtifactLink{}).
		Where("target_type = ? AND target_id = ? AND historical = ?", models.LinkRole, roleID, false).
		Update("historical", true).Error
	if err != nil {
		return fmt.Errorf("historicizing role %d's sources: %w", roleID, err)
	}
	return nil
}

// PasteInput is listing content the recruiter supplied themselves.
type PasteInput struct {
	RoleID uint `json:"roleId"`
	// InitiativeID puts the listing in a workspace as well as on the role, the
	// same way a discovered listing lands in both. Without it the role has
	// evidence that no initiative can see.
	InitiativeID uint   `json:"initiativeId"`
	Text         string `json:"text"`
	Name         string `json:"name"`
}

// Paste stores listing content a person supplied.
//
// Its source says a person pasted it. It is not marked as retrieved from the
// listing, because nothing verified that it was — and a fallback that claimed
// automated provenance would be worse than no fallback.
func (s *DiscoveryService) Paste(in PasteInput) (*models.Artifact, error) {
	if strings.TrimSpace(in.Text) == "" {
		return nil, fmt.Errorf("there is nothing to paste")
	}
	var role models.Role
	if err := s.db.First(&role, in.RoleID).Error; err != nil {
		return nil, fmt.Errorf("loading role %d: %w", in.RoleID, err)
	}
	name := firstNonEmpty(in.Name, role.Title+" (pasted)")
	artifact, err := s.artifacts.create(name, "", "recruiter paste", []byte(in.Text),
		models.LinkRole, in.RoleID)
	if err != nil {
		return nil, err
	}
	if in.InitiativeID != 0 {
		if err := s.artifacts.Link(artifact.ID, models.LinkInitiative, in.InitiativeID); err != nil {
			return nil, err
		}
	}
	return artifact, nil
}

// Fetch would retrieve a page directly. It always refuses, so it returns only
// the refusal.
//
// The signature is honest about the shipped state: deny-by-default with an
// empty allowlist means there is no content to return, and a function promising
// content it can never produce invites a caller to build around the promise.
// Whoever adds the first reviewed source changes this signature, which is the
// right amount of friction for that change.
func (s *DiscoveryService) Fetch(rawURL string) error {
	if err := platform.FetchAllowed(rawURL); err != nil {
		return err
	}
	return fmt.Errorf("direct fetching is not implemented in this build — paste the listing instead")
}

// RoleLifecycle is a discovered role's state, computed against the clock.
type RoleLifecycle struct {
	RoleID uint   `json:"roleId"`
	State  string `json:"state"`
	Reason string `json:"reason"`
}

// Lifecycle reports whether a discovered role is still current.
func (s *DiscoveryService) Lifecycle(roleID uint) (*RoleLifecycle, error) {
	var role models.Role
	if err := s.db.First(&role, roleID).Error; err != nil {
		return nil, fmt.Errorf("loading role %d: %w", roleID, err)
	}
	out := &RoleLifecycle{RoleID: roleID, State: string(models.RoleActive)}
	now := s.now()

	if closing := strings.TrimSpace(string(role.ClosingOn)); closing != "" {
		if day, err := time.Parse("2006-01-02", closing); err == nil {
			// Past the closing date: the listing is closed whenever it was seen.
			if now.After(day.AddDate(0, 0, 1)) {
				out.State = string(models.RoleStale)
				out.Reason = "the listing's closing date has passed"
				return out, nil
			}
		}
	}
	if role.RetrievedAt != nil && now.Sub(*role.RetrievedAt) > staleAfter {
		out.State = string(models.RoleStale)
		out.Reason = "this listing has not been seen for thirty days"
		return out, nil
	}
	return out, nil
}

// Searches lists an initiative's sent searches, newest first, so a shortlist
// can be traced to the query that produced it.
func (s *DiscoveryService) Searches(initiativeID uint) ([]models.Search, error) {
	rows := []models.Search{}
	err := s.db.Where("initiative_id = ? AND task = ?", initiativeID, models.TaskRoleSearch).
		Order("sent_at desc, id desc").Find(&rows).Error
	if err != nil {
		return nil, fmt.Errorf("listing searches: %w", err)
	}
	return rows, nil
}

// Disclosures lists the audit events, newest first.
func (s *DiscoveryService) Disclosures() ([]models.DisclosureEvent, error) {
	rows := []models.DisclosureEvent{}
	if err := s.db.Order("occurred_at desc, id desc").Find(&rows).Error; err != nil {
		return nil, fmt.Errorf("listing disclosure events: %w", err)
	}
	return rows, nil
}

// CurrentSources lists a role's sources, saying which are historical — they
// stay visible for provenance and leave current retrieval.
func (s *DiscoveryService) CurrentSources(roleID uint) ([]models.ArtifactLink, error) {
	rows := []models.ArtifactLink{}
	err := s.db.Where("target_type = ? AND target_id = ?", models.LinkRole, roleID).
		Order("id asc").Find(&rows).Error
	if err != nil {
		return nil, fmt.Errorf("listing role %d's sources: %w", roleID, err)
	}
	return rows, nil
}

// fingerprint is the content identity of a listing.
func fingerprint(text string) string {
	trimmed := strings.Join(strings.Fields(text), " ")
	if trimmed == "" {
		return ""
	}
	sum := sha256.Sum256([]byte(trimmed))
	return hex.EncodeToString(sum[:])
}

// searchReason turns a provider failure into a stored code.
func searchReason(err error) string {
	switch {
	case errors.Is(err, platform.ErrSearchRateLimited):
		return models.ReasonRateLimited
	case errors.Is(err, platform.ErrSearchTimeout):
		return models.ReasonSearchTimeout
	case errors.Is(err, platform.ErrSearchOffline):
		return models.ReasonOffline
	case errors.Is(err, platform.ErrSearchUnauthorized):
		return models.ReasonUnauthorized
	}
	return models.ReasonMalformed
}

func containsType(list []profile.AspectType, want profile.AspectType) bool {
	for _, t := range list {
		if t == want {
			return true
		}
	}
	return false
}

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}
